# Generated by Django 4.2.10 on 2024-03-21 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("true_number", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spamcontact",
            name="spam_count",
        ),
    ]
